<!-- Filename: /module/Blog/view/blog/write/add.phtml -->
<h1>WriteController::editAction()</h1>
<?php
/*
$form = $this->form;
#$form->setAttribute('action', $this->url('blog/edit', array(), true));
$form->prepare();

$form->get('submit')->setValue('Update Post');

echo $this->form()->openTag($form);

echo $this->formCollection($form);

echo $this->form()->closeTag();
*/

$form = $this->form;
$form->setAttribute('action', $this->url());
$form->setAttribute('method', 'POST');   # ist standard
$form->prepare();

echo $this->form()->openTag($form);

#  echo $this->form()->getView()->formCollection($form);
echo $this->formCollection($form);

echo $this->form()->closeTag();